// grove publish — Push branch + create draft PR for a completed task
import { existsSync } from "node:fs";
import { getDb } from "../core/db";
import type { Database } from "../core/db";
import { configRepoDetail } from "../core/config";
import * as ui from "../core/ui";
import * as prompts from "../core/prompts";
import { EventType, TaskStatus } from "../types";
import type { Command, Task } from "../types";

const DIFF_CAP = 50_000;
const PR_FOOTER = (taskId: string) =>
  `\n\n---\nGenerated by [Grove](https://github.com/bpamiri/grove) | Task: ${taskId}`;

/**
 * Generate a PR body using Claude CLI to summarize the diff.
 * Falls back to session_summary if Claude fails or diff is empty.
 */
export async function generatePrBody(
  worktreePath: string,
  taskId: string,
  sessionSummary: string | null,
): Promise<string> {
  let diff = "";

  if (existsSync(worktreePath)) {
    // Try main...HEAD first
    const diffResult = Bun.spawnSync(
      ["git", "diff", "main...HEAD"],
      { cwd: worktreePath },
    );
    if (diffResult.exitCode === 0) {
      diff = diffResult.stdout.toString();
    }

    // Fallback: count commits and diff HEAD~n
    if (!diff) {
      const logResult = Bun.spawnSync(
        ["git", "log", "--oneline", "main..HEAD"],
        { cwd: worktreePath },
      );
      const commitCount = logResult.stdout.toString().trim().split("\n").filter(Boolean).length;
      if (commitCount > 0) {
        const altDiff = Bun.spawnSync(
          ["git", "diff", `HEAD~${commitCount}`],
          { cwd: worktreePath },
        );
        if (altDiff.exitCode === 0) diff = altDiff.stdout.toString();
      }
    }
  }

  // Cap diff size
  if (diff.length > DIFF_CAP) {
    diff = diff.slice(0, DIFF_CAP) + "\n\n[... diff truncated at 50K chars ...]";
  }

  // If we have a meaningful diff, try Claude for a summary
  if (diff.length > 100) {
    const prompt = [
      "Write a concise pull request description for these code changes.",
      "Include a ## Summary section with 2-3 bullet points and a ## Test plan section with a checklist.",
      "Do not include a title. Output only the PR body in markdown.",
      "",
      "```diff",
      diff,
      "```",
    ].join("\n");

    const claudeResult = Bun.spawnSync(
      ["claude", "-p", prompt, "--max-turns", "1", "--output-format", "text"],
      { cwd: worktreePath, stdin: "ignore" },
    );

    if (claudeResult.exitCode === 0) {
      const body = claudeResult.stdout.toString().trim();
      if (body.length > 20) {
        return body + PR_FOOTER(taskId);
      }
    }
  }

  // Fallback: use session summary
  const fallback = sessionSummary || "No description available.";
  return `## Summary\n\n${fallback}${PR_FOOTER(taskId)}`;
}

/**
 * Push branch and create a draft PR for a task.
 * Returns true on success, false on failure (task stays at current status).
 */
export async function publishTask(taskId: string, db: Database): Promise<boolean> {
  const task = db.taskGet(taskId);
  if (!task) {
    ui.warn(`Publish: task ${taskId} not found.`);
    return false;
  }

  const { branch, worktree_path, repo, title, session_summary } = task;

  // Validate prerequisites
  if (!branch) {
    ui.warn(`Publish: task ${taskId} has no branch.`);
    return false;
  }
  if (!repo) {
    ui.warn(`Publish: task ${taskId} has no repo.`);
    return false;
  }
  if (!worktree_path || !existsSync(worktree_path)) {
    ui.warn(`Publish: worktree not found for ${taskId}.`);
    return false;
  }

  // Resolve GitHub repo string
  const repoConfigs = configRepoDetail();
  const rc = repoConfigs[repo];
  if (!rc) {
    ui.warn(`Publish: repo '${repo}' not in config.`);
    return false;
  }
  const ghRepo = rc.github || `${rc.org}/${repo}`;

  // Check for existing PR on this branch
  const existingCheck = Bun.spawnSync([
    "gh", "pr", "list",
    "--repo", ghRepo,
    "--head", branch,
    "--json", "number,url",
    "--limit", "1",
  ]);

  if (existingCheck.exitCode === 0) {
    try {
      const existing = JSON.parse(existingCheck.stdout.toString());
      if (Array.isArray(existing) && existing.length > 0) {
        const pr = existing[0];
        ui.info(`PR already exists: #${pr.number} ${pr.url}`);
        db.taskSet(taskId, "pr_number", pr.number);
        db.taskSet(taskId, "pr_url", pr.url);
        if (task.status === "done") {
          db.taskSetStatus(taskId, TaskStatus.Review);
        }
        return true;
      }
    } catch {
      // Parse failed, continue to create
    }
  }

  // Push the branch
  ui.info(`Pushing ${branch}...`);
  const pushResult = Bun.spawnSync(
    ["git", "push", "-u", "origin", branch],
    { cwd: worktree_path },
  );

  if (pushResult.exitCode !== 0) {
    ui.warn(`Push failed: ${pushResult.stderr.toString().trim()}`);
    return false;
  }

  // Generate PR body (AI summary with fallback)
  ui.info("Generating PR description...");
  const prBody = await generatePrBody(worktree_path, taskId, session_summary);

  // Create draft PR
  const prTitle = `grove(${taskId}): ${title}`;
  ui.info(`Creating draft PR: ${prTitle}`);

  const createResult = Bun.spawnSync([
    "gh", "pr", "create",
    "--repo", ghRepo,
    "--title", prTitle,
    "--body", prBody,
    "--head", branch,
    "--draft",
  ]);

  if (createResult.exitCode !== 0) {
    ui.warn(`PR creation failed: ${createResult.stderr.toString().trim()}`);
    ui.warn(`Branch is pushed. Create the PR manually or retry with: grove publish ${taskId}`);
    return false;
  }

  // Parse PR URL from stdout (gh pr create outputs the URL)
  const prUrl = createResult.stdout.toString().trim();

  // Extract PR number from URL
  let prNumber = 0;
  const urlMatch = prUrl.match(/\/pull\/(\d+)/);
  if (urlMatch) {
    prNumber = parseInt(urlMatch[1], 10);
  }

  // Store PR info
  if (prUrl) db.taskSet(taskId, "pr_url", prUrl);
  if (prNumber) db.taskSet(taskId, "pr_number", prNumber);
  db.addEvent(taskId, EventType.PrCreated, `Draft PR created: ${prUrl}`);

  // Move to review status
  if (task.status === "done") {
    db.taskSetStatus(taskId, TaskStatus.Review);
  }

  ui.success(`PR created: ${prUrl}`);
  return true;
}

// ---------------------------------------------------------------------------
// Command entry point
// ---------------------------------------------------------------------------

export const publishCommand: Command = {
  name: "publish",
  description: "Push branch and create a draft PR for a completed task",

  async run(args: string[]) {
    const db = getDb();

    let taskId = "";

    for (const arg of args) {
      if (arg === "-h" || arg === "--help") {
        console.log(this.help!());
        return;
      }
      if (!arg.startsWith("-") && !taskId) {
        taskId = arg;
      }
    }

    if (taskId) {
      // Publish a specific task
      if (!db.taskExists(taskId)) {
        ui.die(`Task not found: ${taskId}`);
      }
      const task = db.taskGet(taskId)!;
      if (task.status !== "done" && task.status !== "review") {
        ui.die(`Task ${taskId} is '${task.status}'. Must be 'done' or 'review' to publish.`);
      }

      const ok = await publishTask(taskId, db);
      if (!ok) {
        ui.error(`Publish failed for ${taskId}.`);
        process.exit(1);
      }
      return;
    }

    // No task ID: find all done tasks with a branch
    const doneTasks = db.all<Task>(
      "SELECT * FROM tasks WHERE status = 'done' AND branch IS NOT NULL ORDER BY updated_at DESC",
    );

    if (doneTasks.length === 0) {
      ui.info("No tasks ready to publish.");
      return;
    }

    ui.header("Tasks ready to publish");
    for (let i = 0; i < doneTasks.length; i++) {
      const t = doneTasks[i];
      console.log(`  ${ui.bold(`[${i + 1}]`)} ${ui.dim(t.id)} ${ui.dim(t.repo || "")}  ${t.title}`);
    }

    console.log();

    const confirmed = await prompts.confirm(`Publish all ${doneTasks.length} task(s)?`);
    if (!confirmed) return;

    let published = 0;
    for (const t of doneTasks) {
      const ok = await publishTask(t.id, db);
      if (ok) published++;
    }

    ui.success(`Published ${published}/${doneTasks.length} task(s).`);
  },

  help() {
    return [
      "Usage: grove publish [TASK_ID]",
      "",
      "Push a task's branch to remote and create a draft pull request.",
      "",
      "If TASK_ID is given, publish that specific task.",
      "If no TASK_ID, list all 'done' tasks with branches and offer to publish all.",
      "",
      "The PR body is AI-generated from the git diff. If Claude fails,",
      "the session summary is used as a fallback.",
      "",
      "This command is called automatically after a worker completes successfully.",
      "Use it manually to retry failed publishes or publish tasks completed via",
      "other means.",
      "",
      "The task must be in 'done' or 'review' status.",
    ].join("\n");
  },
};
