#!/usr/bin/env bun
// Reads web/dist/ and generates src/broker/web-assets.generated.ts
// so that the compiled binary can serve the SPA without filesystem access.

import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, extname, relative } from "node:path";

const DIST_DIR = join(import.meta.dir, "../web/dist");
const OUT_FILE = join(import.meta.dir, "../src/broker/web-assets.generated.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walk(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const files = walk(DIST_DIR);
const entries: string[] = [];

for (const file of files) {
  const routePath = "/" + relative(DIST_DIR, file);
  const ext = extname(file);
  const contentType = MIME_TYPES[ext] || "application/octet-stream";
  const data = readFileSync(file);
  const b64 = data.toString("base64");

  entries.push(
    `  ${JSON.stringify(routePath)}: { data: Buffer.from(${JSON.stringify(b64)}, "base64"), contentType: ${JSON.stringify(contentType)} },`
  );
}

const source = `// AUTO-GENERATED by scripts/embed-web.ts — do not edit
export const EMBEDDED_ASSETS: Record<string, { data: Buffer; contentType: string }> = {
${entries.join("\n")}
};
`;

await Bun.write(OUT_FILE, source);
console.log(`Embedded ${files.length} files into ${OUT_FILE}`);
