#!/usr/bin/env bun
// Reads skills/*/ and generates src/skills/bundled-skills.generated.ts
// so that the compiled binary can bootstrap skills without filesystem access.

import { readdirSync, readFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import { parse as parseYaml } from "yaml";

const SKILLS_DIR = join(import.meta.dir, "../skills");
const OUT_FILE = join(import.meta.dir, "../src/skills/bundled-skills.generated.ts");

if (!existsSync(SKILLS_DIR)) {
  console.error(`Skills directory not found: ${SKILLS_DIR}`);
  process.exit(1);
}

const skills: Record<string, Record<string, string>> = {};

for (const entry of readdirSync(SKILLS_DIR, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;

  const skillDir = join(SKILLS_DIR, entry.name);
  const manifestPath = join(skillDir, "skill.yaml");
  if (!existsSync(manifestPath)) continue;

  const manifestRaw = readFileSync(manifestPath, "utf-8");
  let manifest: { name: string; files?: string[] };
  try {
    manifest = parseYaml(manifestRaw);
  } catch {
    console.warn(`Skipping ${entry.name}: invalid skill.yaml`);
    continue;
  }

  const files: Record<string, string> = {};
  files["skill.yaml"] = manifestRaw;

  for (const file of manifest.files ?? []) {
    const filePath = join(skillDir, file);
    if (!existsSync(filePath)) {
      console.warn(`Skipping file ${file} in ${entry.name}: not found`);
      continue;
    }
    files[file] = readFileSync(filePath, "utf-8");
  }

  skills[manifest.name ?? entry.name] = files;
}

const entries = Object.entries(skills).map(([name, files]) => {
  const fileEntries = Object.entries(files)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");
  return `  ${JSON.stringify(name)}: {\n${fileEntries}\n  },`;
});

const source = `// AUTO-GENERATED by scripts/embed-skills.ts — do not edit
import type { EmbeddedSkills } from "./library";

export const BUNDLED_SKILLS: EmbeddedSkills = {
${entries.join("\n")}
};
`;

await Bun.write(OUT_FILE, source);
console.log(`Embedded ${Object.keys(skills).length} skills into ${relative(join(import.meta.dir, ".."), OUT_FILE)}`);
