name = "grove-cloud"
main = "src/index.ts"
compatibility_date = "2026-03-28"

routes = [
  { pattern = "grove.cloud/*", zone_name = "grove.cloud" },
  { pattern = "*.grove.cloud/*", zone_name = "grove.cloud" }
]

[[kv_namespaces]]
binding = "GROVE_ROUTES"
id = "f5178e934c1c4bd2b9bf3ed02d614039"
